name: Update website code

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: resume-frontend-vite

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'
        cache-dependency-path: resume-frontend-vite/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build Vite app
      run: npm run build

    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2
        verbose: false
        arch: amd64
        rootdir: ""
        workdir: ""

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC

    - name: Invalidate Cloudfront Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

    - name: Upload to S3
      run: aws s3 sync ./dist/ s3://lanceriver.com/ --delete --exact-timestamps
